// utils/fakeAiList.ts
export const fakeAiList = [
  { id: 'ai_1', name: '终结者', level: '20', status: '空闲', avatar: '🤖' },
  { id: 'ai_2', name: '神秘大师', level: '19', status: '空闲', avatar: '👨‍🚀' },
  { id: 'ai_11', name: '影子程序', level: '18', status: '空闲', avatar: '👤' },
  { id: 'ai_14', name: '量子黑客', level: '17', status: '匹配中', avatar: '🧬' },
  { id: 'ai_3', name: '狂热棋士', level: '16', status: '匹配中', avatar: '🧠' },
  { id: 'ai_12', name: '暴走逻辑', level: '15', status: '匹配中', avatar: '🌀' },
  { id: 'ai_13', name: '智能巡航', level: '14', status: '空闲', avatar: '🚀' },
  { id: 'ai_4', name: '冰冷逻辑', level: '13', status: '空闲', avatar: '❄️' },
  { id: 'ai_15', name: '未来特工', level: '12', status: '空闲', avatar: '🕶️' },
  { id: 'ai_5', name: '快手小子', level: '11', status: '匹配中', avatar: '⚡' },
  { id: 'ai_16', name: '规则破坏者', level: '10', status: '匹配中', avatar: '💥' },
  { id: 'ai_6', name: '沉默猎手', level: '9', status: '空闲', avatar: '🎯' },
  { id: 'ai_17', name: '冷静大师', level: '8', status: '空闲', avatar: '🧊' },
  { id: 'ai_7', name: '风暴先锋', level: '7', status: '空闲', avatar: '🌪️' },
  { id: 'ai_8', name: '老练战士', level: '6', status: '匹配中', avatar: '🧓' },
  { id: 'ai_18', name: '数据幽灵', level: '5', status: '空闲', avatar: '👻' },
  { id: 'ai_9', name: '新手学徒', level: '4', status: '空闲', avatar: '🐣' },
  { id: 'ai_19', name: '零号机', level: '3', status: '匹配中', avatar: '0️⃣' },
  { id: 'ai_20', name: '初代模型', level: '2', status: '空闲', avatar: '📦' },
  { id: 'ai_10', name: '棋局测试机', level: '1', status: '空闲', avatar: '🔧' },
];