// utils/fakeAiList.ts
export const fakeAiList = [
  { id: 'ai_1', name: 'The Terminator', level: '20', status: 'Available', avatar: '🤖' },
  { id: 'ai_2', name: 'Mystery Master', level: '19', status: 'Available', avatar: '👨‍🚀' },
  { id: 'ai_11', name: 'Shadow Protocol', level: '18', status: 'Available', avatar: '👤' },
  { id: 'ai_14', name: 'Quantum Hacker', level: '17', status: 'Available', avatar: '🧬' },
  { id: 'ai_3', name: 'Chess Fanatic', level: '16', status: 'Available', avatar: '🧠' },
  { id: 'ai_12', name: 'Rogue Logic', level: '15', status: 'In Match', avatar: '🌀' },
  { id: 'ai_13', name: 'Smart Cruiser', level: '14', status: 'Available', avatar: '🚀' },
  { id: 'ai_4', name: 'Cold Logic', level: '13', status: 'In Match', avatar: '❄️' },
  { id: 'ai_15', name: 'Future Agent', level: '12', status: 'Available', avatar: '🕶️' },
  { id: 'ai_5', name: 'Quick Kid', level: '11', status: 'In Match', avatar: '⚡' },
  { id: 'ai_16', name: 'Rule Breaker', level: '10', status: 'Available', avatar: '💥' },
  { id: 'ai_6', name: 'Silent Hunter', level: '9', status: 'Available', avatar: '🎯' },
  { id: 'ai_17', name: 'Calm Master', level: '8', status: 'Available', avatar: '🧊' },
  { id: 'ai_7', name: 'Storm Vanguard', level: '7', status: 'Available', avatar: '🌪️' },
  { id: 'ai_8', name: 'Veteran Warrior', level: '6', status: 'Available', avatar: '🧓' },
  { id: 'ai_18', name: 'Data Ghost', level: '5', status: 'In Match', avatar: '👻' },
  { id: 'ai_9', name: 'Rookie Apprentice', level: '4', status: 'Available', avatar: '🐣' },
  { id: 'ai_19', name: 'Unit Zero', level: '3', status: 'In Match', avatar: '0️⃣' },
  { id: 'ai_20', name: 'Proto Model', level: '2', status: 'Available', avatar: '📦' },
  { id: 'ai_10', name: 'Test Bot', level: '1', status: 'Available', avatar: '🔧' },
];